import Layout from "@/components/layout/Layout";
import { BarChart3, CheckCircle2, Database, Download, Fuel, Leaf, MapPinned, Settings2, Upload } from "lucide-react";
import { isSupabaseConfigured } from "@/lib/supabase";

const config={
 energy:{title:"Energy analytics",desc:"Analyze consumption, demand, efficiency and generator loading across all COW sites.",icon:BarChart3,kpis:[["Total consumption","778.4 MWh"],["Peak demand","4.86 MW"],["Avg. site load","6.2 kW"],["Energy intensity","1.39 MWh/site"]]},
 emissions:{title:"CO₂ emissions",desc:"Track direct and indirect emissions against baseline and reduction targets.",icon:Leaf,kpis:[["Total emissions","1,562 tCO₂e"],["Scope 1","1,416 tCO₂e"],["Scope 2","146 tCO₂e"],["Avoided emissions","54.2 tCO₂e"]]},
 fuel:{title:"Fuel management",desc:"Plan refueling, monitor tank levels and manage access for generator-powered sites.",icon:Fuel,kpis:[["Monthly fuel","584,260 L"],["Sites below 30%","31"],["Planned deliveries","46"],["7-day demand","138,400 L"]]},
 sites:{title:"Sites & map",desc:"National view of energy assets, connectivity and operational readiness.",icon:MapPinned,kpis:[["Total COWs","561"],["Reporting","543"],["Generator sites","349"],["SEC / Hybrid","212"]]},
 settings:{title:"System settings",desc:"Configure data sources, thresholds, users and Supabase integration.",icon:Settings2,kpis:[["Authentication",isSupabaseConfigured?"Connected":"Preview mode"],["Database",isSupabaseConfigured?"Connected":"Not configured"],["Refresh interval","10 minutes"],["Environment","Production ready"]]},
};
export default function ModulePage({module}:{module:keyof typeof config}){const c=config[module];const Icon=c.icon;return <Layout title={c.title} description={c.desc}><section className="module-hero"><div className="module-icon"><Icon/></div><div><span className="eyebrow purple">{module==="settings"?"Administration":"Operational module"}</span><h2>{module==="settings"?"Connect your data platform":"Live national visibility"}</h2><p>{module==="settings"?"Add the two Vite environment variables, apply the included database schema, and the application will switch from preview mode to Supabase authentication and data access.":"Filters, exports and detailed drill-downs are prepared for the Supabase data model."}</p></div><button><Download/>Export report</button></section><section className="mini-kpi-grid">{c.kpis.map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</section>{module==="settings"?<Setup/>:<DataPreview module={module}/>}</Layout>}
function Setup(){return <section className="panel setup-panel"><div className="panel-head"><div><h2>Supabase onboarding</h2><p>Complete these steps when the project is ready.</p></div></div><ol className="setup-steps"><li><span>1</span><div><strong>Create the Supabase project</strong><p>Apply <code>supabase/schema.sql</code> in the SQL editor.</p></div><CheckCircle2/></li><li><span>2</span><div><strong>Configure environment variables</strong><p>Set <code>VITE_SUPABASE_URL</code> and <code>VITE_SUPABASE_ANON_KEY</code>.</p></div><Database/></li><li><span>3</span><div><strong>Import operational data</strong><p>Load sites, energy readings, fuel transactions and alerts.</p></div><Upload/></li></ol></section>}
function DataPreview({module}:{module:string}){const rows=module==="fuel"?[["COW536","Central","18%","24 Sep 2026","Critical"],["COW731","West","34%","22 Sep 2026","Attention"],["COW422","South","46%","25 Sep 2026","Planned"]]:[["COW075","Central","6.8 kW","1.2 tCO₂e","Healthy"],["COW529","East","5.1 kW","0.4 tCO₂e","Healthy"],["COW731","West","8.4 kW","1.8 tCO₂e","Attention"]];return <section className="panel module-table"><div className="panel-head"><div><h2>{module==="fuel"?"Upcoming fueling plan":"Site performance"}</h2><p>Sample preview · Supabase rows will replace this dataset automatically.</p></div><button>Filter</button></div><div className="data-table"><table><thead><tr>{(module==="fuel"?["Site","Region","Tank","Next fueling","Status"]:["Site","Region","Average load","CO₂ / day","Status"]).map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r[0]}>{r.map((v,i)=><td key={v}>{i===0?<strong>{v}</strong>:i===4?<span className={`status ${v.toLowerCase()}`}>{v}</span>:v}</td>)}</tr>)}</tbody></table></div></section>}
