import Layout from "@/components/layout/Layout";
import { AlertTriangle, ArrowDownRight, ArrowUpRight, BatteryCharging, Droplets, Fuel, Leaf, MapPin, Zap } from "lucide-react";
import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useNavigate } from "react-router-dom";

const trend=[{m:"Apr",energy:640,fuel:515},{m:"May",energy:690,fuel:540},{m:"Jun",energy:750,fuel:590},{m:"Jul",energy:720,fuel:555},{m:"Aug",energy:810,fuel:620},{m:"Sep",energy:778,fuel:584}];
const sources=[{name:"Generator",value:62,color:"#ff375e"},{name:"Grid / SEC",value:29,color:"#00c8b4"},{name:"Hybrid",value:9,color:"#ffb000"}];
const sites=[{id:"COW536",region:"Central",source:"Generator",fuel:18,load:84,status:"Critical"},{id:"COW075",region:"Central",source:"Hybrid",fuel:72,load:61,status:"Healthy"},{id:"COW731",region:"West",source:"Generator",fuel:34,load:78,status:"Attention"},{id:"COW529",region:"East",source:"SEC",fuel:100,load:55,status:"Healthy"},{id:"COW422",region:"South",source:"Generator",fuel:46,load:69,status:"Attention"}];

export default function Overview(){const navigate=useNavigate();return <Layout title="Energy command center" description="National performance across COW sites, energy sources and fuel operations.">
  <section className="metric-grid">
    <Metric icon={<Zap/>} color="cyan" title="Energy consumption" value="778.4" unit="MWh" delta="4.8%" up detail="vs. previous month"/>
    <Metric icon={<Fuel/>} color="orange" title="Diesel consumption" value="584,260" unit="L" delta="2.1%" detail="vs. previous month"/>
    <Metric icon={<Leaf/>} color="green" title="CO₂ emissions" value="1,562" unit="tCO₂e" delta="3.4%" detail="reduction vs. baseline" positive/>
    <Metric icon={<MapPin/>} color="purple" title="Sites monitored" value="561" unit="COWs" delta="96.8%" detail="reporting coverage" positive/>
  </section>
  <section className="dashboard-grid">
    <article className="panel span-2"><PanelHead title="Energy & fuel trend" subtitle="Monthly national consumption" action="View analytics" onClick={()=>navigate('/energy')}/><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend}><defs><linearGradient id="energy" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#4f0f83" stopOpacity={.32}/><stop offset="1" stopColor="#4f0f83" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#e9e5ed" vertical={false}/><XAxis dataKey="m" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip/><Area type="monotone" dataKey="energy" stroke="#4f0f83" strokeWidth={3} fill="url(#energy)"/><Area type="monotone" dataKey="fuel" stroke="#ff375e" strokeWidth={2} fill="transparent" strokeDasharray="5 5"/></AreaChart></ResponsiveContainer></div><div className="chart-legend"><span><i className="purple-dot"/>Energy MWh</span><span><i className="red-dot"/>Fuel ×1,000 L</span></div></article>
    <article className="panel"><PanelHead title="Power source mix" subtitle="Active site distribution"/><div className="donut"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={sources} dataKey="value" innerRadius={62} outerRadius={88} paddingAngle={4}>{sources.map(x=><Cell key={x.name} fill={x.color}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><div><strong>561</strong><small>sites</small></div></div><div className="source-list">{sources.map(x=><div key={x.name}><span><i style={{background:x.color}}/>{x.name}</span><strong>{x.value}%</strong></div>)}</div></article>
    <article className="panel"><PanelHead title="Fuel readiness" subtitle="Generator-connected sites" action="Manage fuel" onClick={()=>navigate('/fuel')}/><div className="fuel-gauge"><div><Droplets/><strong>68%</strong><span>Average tank level</span></div></div><div className="readiness-row"><span><i className="ok"/>Ready <strong>318</strong></span><span><i className="warn"/>Low <strong>24</strong></span><span><i className="danger"/>Critical <strong>7</strong></span></div></article>
    <article className="panel span-2"><PanelHead title="Site operational status" subtitle="Priority sites requiring monitoring" action="All sites" onClick={()=>navigate('/sites')}/><div className="data-table"><table><thead><tr><th>Site</th><th>Region</th><th>Power source</th><th>Fuel level</th><th>Gen. load</th><th>Status</th></tr></thead><tbody>{sites.map(s=><tr key={s.id}><td><strong>{s.id}</strong></td><td>{s.region}</td><td>{s.source}</td><td><div className="mini-progress"><span style={{width:`${s.fuel}%`}} className={s.fuel<25?'critical':''}/></div>{s.fuel}%</td><td>{s.load}%</td><td><span className={`status ${s.status.toLowerCase()}`}>{s.status}</span></td></tr>)}</tbody></table></div></article>
    <article className="panel alerts-panel"><PanelHead title="Active alerts" subtitle="7 require attention"/><div className="alert-item critical"><AlertTriangle/><div><strong>Critical fuel level</strong><span>COW536 · 18% remaining</span></div><small>12m</small></div><div className="alert-item warning"><BatteryCharging/><div><strong>High generator load</strong><span>COW731 · 78% load factor</span></div><small>36m</small></div><div className="alert-item"><Zap/><div><strong>Consumption anomaly</strong><span>COW422 · +22% vs baseline</span></div><small>1h</small></div></article>
  </section>
</Layout>}

function Metric({icon,color,title,value,unit,delta,detail,up,positive}:{icon:React.ReactNode;color:string;title:string;value:string;unit:string;delta:string;detail:string;up?:boolean;positive?:boolean}){return <article className="metric-card"><div className={`metric-icon ${color}`}>{icon}</div><div className="metric-title">{title}</div><div className="metric-value">{value}<span>{unit}</span></div><div className={`metric-delta ${positive?'positive':up?'negative':''}`}>{positive||!up?<ArrowDownRight/>:<ArrowUpRight/>}<strong>{delta}</strong><span>{detail}</span></div></article>}
function PanelHead({title,subtitle,action,onClick}:{title:string;subtitle:string;action?:string;onClick?:()=>void}){return <div className="panel-head"><div><h2>{title}</h2><p>{subtitle}</p></div>{action&&<button onClick={onClick}>{action} →</button>}</div>}
