import Header from "./Header";
import { NavLink } from "react-router-dom";
import { BarChart3, FileBarChart, Fuel, Gauge, Leaf, MapPinned, Settings, X } from "lucide-react";
import { useState } from "react";
const navigation = [{to:"/",label:"Overview",icon:Gauge,end:true},{to:"/energy",label:"Energy analytics",icon:BarChart3},{to:"/emissions",label:"CO₂ emissions",icon:Leaf},{to:"/fuel",label:"Fuel management",icon:Fuel},{to:"/sites",label:"Sites & map",icon:MapPinned},{to:"/reports",label:"Reports",icon:FileBarChart}];
export default function Layout({ children, title, description }: { children: React.ReactNode; title?: string; description?: string }) {
  const [mobileNav,setMobileNav]=useState(false);
  return <div className="app-shell"><aside className={mobileNav?"app-sidebar open":"app-sidebar"}><div className="sidebar-brand"><div className="stc-wordmark">stc</div><button onClick={()=>setMobileNav(false)}><X/></button></div><div className="product-name"><span>COW Energy</span><small>Management Platform</small></div><nav>{navigation.map(item=><NavLink key={item.to} to={item.to} end={item.end} onClick={()=>setMobileNav(false)}><item.icon/><span>{item.label}</span></NavLink>)}</nav><div className="sidebar-bottom"><NavLink to="/settings"><Settings/><span>Settings</span></NavLink><div className="system-health"><i/>All systems operational</div><small>Powered by ACES MSD</small></div></aside>{mobileNav&&<button className="nav-backdrop" onClick={()=>setMobileNav(false)} aria-label="Close navigation"/>}<div className="app-main"><Header onMenu={()=>setMobileNav(true)}/><main className="page-content">{title&&<div className="page-title"><div><span className="eyebrow purple">National operations</span><h1>{title}</h1>{description&&<p>{description}</p>}</div><span className="live-pill"><i/>Live</span></div>}{children}</main><footer className="app-footer">© 2026 ACES · stc COW Energy Management Platform</footer></div></div>;
}
